name: PatchHound Pipeline

on:
  workflow_call:
    secrets:
      BASE_URL:
        required: true
      ALERT_WEBHOOK:
        required: true
      TOKEN:
        required: true

jobs:
  security-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bblue530/patchhound_cli:latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      ALERT_WEBHOOK: ${{ secrets.ALERT_WEBHOOK }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Check release tags
        id: meta
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            echo "[+] Current tags: ${VERSION}"
            echo "tags=${VERSION}" >> $GITHUB_OUTPUT
          else
            echo "[+] No tag found"
            echo "tags=" >> $GITHUB_OUTPUT
          fi

      - name: PatchHound scan
        if: ${{ steps.meta.outputs.tag != '' }}
        run: |
          patchhound scan --token "$TOKEN" --set-config BASE_URL "$BASE_URL" ALERT_WEBHOOK "$ALERT_WEBHOOK"

      - name: Upload vulnerability summary
        if: ${{ steps.meta.outputs.tag != '' }}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: vulnerability-summary
          path: |
            summary.md
            sbom.cyclonedx.json
            vulns.cyclonedx.json
            prio_vulns.json
            sast_report.json
            trivy_report.json
            path_to_resources_token.txt