name: PatchHound Pipeline

on:
  workflow_call:
    secrets:
      BASE_URL:
        required: true
      ALERT_WEBHOOK:
        required: true
      TOKEN:
        required: true

jobs:
  security-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bblue530/patchhound_cli:latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      ALERT_WEBHOOK: ${{ secrets.ALERT_WEBHOOK }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: PatchHound scan
        run: |
          patchhound scan --token "$TOKEN" --set-config BASE_URL "$BASE_URL" ALERT_WEBHOOK "$ALERT_WEBHOOK"

      - name: Upload vulnerability summary
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-summary
          path: |
            summary.md
            sbom.cyclonedx.json
            vulns.cyclonedx.json
            prio_vulns.json
            sast_report.json
            trivy_report.json
            path_to_resources_token.txt